#!/bin/bash
set -e

source utils

if [ "$1" = 'supervisord' ]; then

  for entrypoint in $(cat "/usr/bin/docker-entrypoint.list"); do

    if [ "${entrypoint:0:1}" != "#" ] && [ -f "/usr/bin/$entrypoint" ]; then

      OUTPUT_SUCCESS "Execute $entrypoint"

      . $entrypoint "$@"

    fi

  done

fi

exec "$@"
