#!/bin/bash
set -e

if [ "$MAGE_MODE" != "production" ]; then

  binaries="
  bin-composer
  bin-mhsendmail
  "

  for binary in $(echo $binaries); do

    while [ ! -f "/usr/bin/$binary" ]; do

      if [ "${binary:0:1}" != "#" ]; then

        (echo >&2 "Waiting for $binary to be ready...")

        sleep 2

      fi

    done

  done

fi
