#!/bin/bash
set -e

COUNTER=1

while [ $COUNTER -le 3 ]
do

  EXIT=0

  PROCESSES=$(supervisorctl pid all)

  for PID in $PROCESSES; do

    if [ "$PID" = "0" ]; then

      EXIT=1

      break

    fi

  done

  if [ "$EXIT" == "0" ]; then

    break

  fi

  COUNTER=$((COUNTER+1))

  sleep 0.2

done

exit $EXIT
