#!/bin/bash
set -e

source utils

EXIT=0

if [ -f "/etc/supervisor/conf.d/server.conf" ]; then

    RESULT=$(CURL_STATUS "$MAGE_HEATH?secret=$APP_SECRET")

    if [ "$RESULT" != "200" ]; then

        EXIT=1

    fi

fi

echo $EXIT
