#!/bin/bash
set -e

binaries="
bin-composer
bin-mhsendmail
"

for binary in $(echo $binaries); do

  if [ "$MAGE_MODE" == "production" ]; then

    rm -rf "/usr/bin/$binary"

  else

    while [ ! -f "/usr/bin/$binary" ]; do

      if [ "${binary:0:1}" != "#" ]; then

        (echo >&2 "Waiting for $binary to be ready...")

        sleep 2

      fi

    done

  fi

done
