#!/bin/bash
set -e

sed -i \
"s/password = rootless/password = $SUPERVISOR_PASSWORD;/" \
"/etc/supervisor/supervisord.conf"

sed -i \
"s/loglevel = warn/loglevel $SUPERVISOR_LOG_LEVEL;/" \
"/etc/supervisor/supervisord.conf"
