#!/bin/bash
set -e

if [ "$USE_SERVER" != "true" ]; then

  rm -f "/etc/supervisor/conf.d/server.conf"

fi

if [ "$USE_CRONTAB" != "true" ]; then

  rm -f "/etc/supervisor/conf.d/crontab.conf"

fi

if [ "$APP_MODE" != "run" ]; then

  rm -rf "/etc/supervisor/conf.d/*"

fi
