#!/bin/bash
set -e

source utils

if [ "$APP_MODE" == "run" ]; then

    until REDIS_CACHE_QUERY "ping" >/dev/null 2>&1; do

        (>&2 echo "Waiting for Redis cache to be ready...")

        sleep 2

    done

    until REDIS_SESSION_QUERY "ping" >/dev/null 2>&1; do

        (>&2 echo "Waiting for Redis session to be ready...")

        sleep 2

    done

fi
