#!/bin/bash
set -e

source utils

if [ "$APP_MODE" == "run" ]; then

  MYSQL_QUERY \
  "CREATE TABLE IF NOT EXISTS $APP_TABLE (
  id INT NOT NULL AUTO_INCREMENT,
  app_name VARCHAR(128) NOT NULL,
  app_uid VARCHAR(128) NOT NULL,
  app_version VARCHAR(16) NOT NULL,
  app_secret VARCHAR(64) NOT NULL,
  is_active TINYINT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  UNIQUE APP_MIGRATION_UNIQUE (app_name ASC, app_uid ASC, app_version ASC, app_secret ASC),
  INDEX APP_MIGRATION_APP_NAME_IS_ACTIVE (app_name ASC, is_active ASC)
  ) ENGINE = InnoDB;"

  if [ "$APP_RECREATE" == "true" ]; then

    MYSQL_QUERY \
    "DELETE FROM $APP_TABLE
    WHERE app_name='$APP_NAME'
    AND app_uid='$APP_UID'
    AND app_version='$APP_VERSION'
    AND app_secret='$APP_SECRET'
    ;"

  fi

  MYSQL_QUERY \
  "UPDATE $APP_TABLE
  SET is_active=0
  WHERE app_name='$APP_NAME'
  AND is_active='1'
  ;"

  COUNTER=$(MYSQL_QUERY \
  "SELECT COUNT(*)
  FROM $APP_TABLE
  WHERE app_name='$APP_NAME'
  AND app_uid='$APP_UID'
  AND app_version='$APP_VERSION'
  AND app_secret='$APP_SECRET'
  ;")

  while [ "$COUNTER" -gt 0 ]; do

    (>&2 echo "App $APP_NAME / version $APP_VERSION / uid $APP_UID / secret $APP_SECRET is all ready running")

    sleep 2

    COUNTER=$(MYSQL_QUERY \
    "SELECT COUNT(*)
    FROM $APP_TABLE
    WHERE app_name='$APP_NAME'
    AND app_uid='$APP_UID'
    AND app_version='$APP_VERSION'
    AND app_secret='$APP_SECRET'
    ;")

  done

  MYSQL_QUERY \
  "INSERT INTO $APP_TABLE (
  app_name,
  app_uid,
  app_version,
  app_secret
  )
  VALUES (
  '$APP_NAME',
  '$APP_UID',
  '$APP_VERSION',
  '$APP_SECRET'
  );"

fi
