#!/bin/bash
set -e

source utils

if [ "$1" = 'supervisord' ]; then

  for ENTRYPOINT in $(cat "/usr/bin/docker-entrypoint.list"); do

    if [ "${ENTRYPOINT:0:1}" != "#" ] && [ -f "/usr/bin/$ENTRYPOINT" ]; then

      . $ENTRYPOINT "$@"

    fi

  done

fi

exec "$@"
