#!/bin/bash
set -e

COUNTER=1

while [ $COUNTER -le 3 ]; do

    EXIT="0"

    for HEALTH in $(cat "/usr/bin/docker-health.list"); do

        if [ "${HEALTH:0:1}" != "#" ] && [ -f "/usr/bin/$HEALTH" ]; then

            EXIT=$(exec $HEALTH "$@")

            if [ "$EXIT" != "0" ]; then

                break

            fi

        fi

    done

    COUNTER=$((COUNTER+1))

    if [ "$EXIT" != "0" ]; then

        sleep 0.2

    fi

done

exit $EXIT
